proj2/app2/urls.py
from django.urls import path,re_path
from app2 import views
# template tagging
app_name = 'app2'

urlpatterns=[
    re_path(r'^users/',views.user,name='users'),
    re_path(r'^formpage/', views.FF, name='form_name'),
    re_path(r'^signup/', views.SU, name='form_model'),
    re_path(r'^register/$',views.register,name='register'),
    re_path(r'^logout/$',views.user_logout,name='logout'),
    re_path(r'^user_login/$',views.user_login,name='user_login')

]

proj2/proj2/urls.py
from django.contrib import admin
from django.urls import path,re_path,include
from app2 import views

urlpatterns = [
    path('admin/', admin.site.urls),
    re_path(r'^$', views.index, name='index'),
    re_path(r'^app2/',include('app2.urls')),
    # re_path(r'^formpage/',views.FF, name='form_name'),
    # re_path(r'^signup/',views.SU, name='form_model')

]

proj2/app2/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Users(models.Model):
    f_name = models.CharField(max_length=264)
    l_name = models.CharField(max_length=264)
    email = models.EmailField(max_length=264, unique=True)

    def __str__(self):
        return self.email

class UserProfileInfo(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE)
    portfolio_site = models.URLField(blank=True)
    profile_pic = models.ImageField(upload_to='profile_pics',blank=True)

    def __str__(self):
        return self.user.username

proj2/app2/forms.py
from django import forms
from django.core import validators
from django.contrib.auth.models import User
from .models import Users,UserProfileInfo

def check_z(value):
    if value[0].lower() != 'z':
        raise forms.ValidationError("must start with z")

class FormName(forms.Form):
    name = forms.CharField(validators=[check_z])
    email = forms.EmailField()
    verify = forms.EmailField()
    text = forms.CharField(widget=forms.Textarea)
    botcatcher = forms.CharField(required=False,
                                 widget=forms.HiddenInput,
                                 validators=[validators.MaxLengthValidator(0)])
    # def clean_botcatcher(self):
    #     botcatcher = self.cleaned_data['botcatcher']
    #     if len(botcatcher)>0:
    #         raise forms.ValidationError("bot detected")
    #     return botcatcher
    def clean(self):
        cleaned_data=super().clean()
        email=cleaned_data["email"]
        vmail=cleaned_data['verify']

        if email != vmail:
            raise  forms.ValidationError("mismatch")

class myForm(forms.ModelForm):
    class Meta():
        model=Users
        fields="__all__"

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta():
        model = User
        fields = ('username','email','password')

class UserProfileInfoForm(forms.ModelForm):
    class Meta():
        model = UserProfileInfo
        fields = ('portfolio_site','profile_pic')

proj2/app2/views.py
from django.shortcuts import render
from  django.http import HttpResponse,HttpResponseRedirect
from app2.models import Users
from . import forms

from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate,login,logout


# Create your views here.
def index(request) :
    # return HttpResponse("<b>Hello World! </b>")
    return render(request,'app2/index.html')

def user(request):

    user_list = Users.objects.order_by('f_name')
    user_dict = {'users': user_list}
    return render(request,'app2/users.html', context=user_dict)

def FF(request):
    form = forms.FormName()
    if request.method == "POST":
        form=forms.FormName(request.POST)
        if form.is_valid():
            print("submitted ")
            print(form.cleaned_data['name'])
            print(form.cleaned_data['email'])
            print(form.cleaned_data['text'])

    return render(request,'app2/form_page.html',{'form':form})

def SU(request):
    form=forms.myForm()
    if request.method == "POST":
        form = forms.myForm(request.POST)
        if form.is_valid():
            form.save(commit=True)
            # return render(request, 'app2/signup.html', {'form': form})
            return index(request)
        else:
            print("invalid form")
    return render(request, 'app2/signup.html', {'form': form})


def register(request):
    registered=False

    if request.method=="POST":
        user_form = forms.UserForm(data=request.POST)
        profile_form = forms.UserProfileInfoForm(data=request.POST)

        if user_form.is_valid() and profile_form.is_valid():

            user = user_form.save()
            user.set_password(user.password)
            user.save()

            profile=profile_form.save(commit=False)
            profile.user=user #one to one relationship in forms

            if 'profile_pic' in request.FILES:
                profile.profile_pic = request.FILES['profile_pic']

            profile.save()

            registered = True
        else:
            print(user_form.errors,profile_form.errors)

    else:
        user_form=forms.UserForm()
        profile_form = forms.UserProfileInfoForm()

    return render(request,'app2/registration.html',
                  {'user_form':user_form,
                   'profile_form':profile_form,
                   'registered':registered})

@login_required
def user_logout(request):
    logout(request)
    return  render(request,'app2/index.html')

def user_login(request):
    if request.method=="POST":
        username=request.POST.get('username')
        password=request.POST.get('password')

        user = authenticate(username=username,password=password)

        if user:
            if user.is_active:
                login(request,user)
                return HttpResponseRedirect(reverse('index'))

            else:
                return HttpResponse("ACCOUNT NOT ACTIVE")
        else:
            print(" failed login attempt ")
            print("Username:{} and passsword {}".format(username,password))
            return HttpResponseRedirect("invalid")

    else:
        return render(request,'app2/login.html',{})

proj2/templates/app2/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Base</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">

<!-- jQuery library -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

<!-- Latest compiled JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>

</head>
<body>
     <nav class="navbar navbar-default navbar-static-top">
      <div class="container">
        <ul class="nav navbar-nav">
          <li><a class="navbar-brand" href="{% url 'index' %}">DJANGO</a></li>
          <li><a class="navbar-link" href="{% url 'admin:index' %}">Admin</a></li>
          <li><a class="navbar-link" href="{% url 'app2:form_model' %}">SignUp</a></li>
          <li><a class="navbar-link" href="{% url 'app2:register' %}">Register</a></li>

          {% if user.is_authenticated %}
            <li><a class="navbar-link" href="{% url 'app2:logout' %}">LOGOUT</a></li>
          {% else %}
            <li><a class="navbar-link" href="{% url 'app2:user_login' %}">LOGIN</a></li>
          {% endif %}

        </ul>
      </div>
    </nav>
    <div class="container">



        {% block body_blok %}
        {# Anything outside of this will be inherited if you use extend.#}
        {% endblock %}
    </div>
</body>
</html>

proj2/templates/app2/form_page.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title> forms </title>
    <!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">

<!-- jQuery library -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

<!-- Latest compiled JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
</head>
<body>
<div class="container">
    <form method="POST">
        {{ form.as_p }}
        {% csrf_token %}
        <input type="submit" class="btn btn-primary" value="submit">


    </form><br>
<!--    <h3>/user for user d</h3>-->
    <a href="{% url 'index' %}"> go to index </a>
</div>
</body>
</html>

proj2/templates/app2/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title> </title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">

<!-- jQuery library -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

<!-- Latest compiled JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>

</head>
<body>
<div class="container">
    <div class="jumbotron">
    <h1>Working properly</h1>
<h3>/user for user data</h3>
    <a href="{% url 'app2:users' %}"> see all users </a>
<h3>/signup for signing up</h3>
    <a href="{% url 'app2:form_model' %}"> signup </a>
<h3>/form_page for viewing form </h3>
    <a href="app2/formpage/"> view form </a>   <!--another way to use urls-->
<h3>/register for viewing form </h3>
    <a href="{% url 'app2:register' %}"> register </a>   <!--another way to use urls-->
<h3>/user_login for logging in </h3>
    <a href="{% url 'app2:user_login' %}"> login </a>
</div>
    </div>
</body>
</html>

proj2/templates/app2/login.html
{% extends 'app2/base.html' %}
{% block body_blok %}
    <div class="jumbotron">
    <h1> login </h1>
    <form action="{% url 'app2:user_login' %}" method="post">
        {% csrf_token %}
        <label for="username">USERNAME:</label>
        <input type="text" name="username" palceholder="">

        <label for="password">PASSWORD:</label>
        <input type="password" name="password">

        <input type="submit" name="" value="login">

    </form>
    </div>

{% endblock %}

proj2/templates/app2/registration.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Registration</title>
</head>
{% extends "app2/base.html" %}

<body>
{% block body_blok %}



<div class="jumbotron">
    {% if registered %}
     <h1> registered </h1>
    {% else %}
        <h1>Register here </h1>
    <h3> fill the form </h3>

    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ user_form.as_p }}
        {{ profile_form.as_p }}
        <input type="submit" name="" value="Register">

    </form>

    {% endif %}


</div>

{% endblock %}


</body>
</html>

proj2/templates/app2/signup.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title> forms </title>
    <!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">

<!-- jQuery library -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

<!-- Latest compiled JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
</head>
<body>
<div class="container">
    <h1>SIGN UP HERE</h1>
    <form method="POST">
        {{ form.as_p }}
        {% csrf_token %}
        <input type="submit" class="btn btn-primary" value="submit">


    </form>

</div>
</body>
</html>>

proj2/templates/app2/users.html
<!DOCTYPE html>
<head>
    <title> users </title>
<!--    if this is declared after extending the base.html , then it will not work-->
</head>
{% extends "app2/base.html" %}

{% load myFilters %}

{% block body_blok %}
<h1> user: </h1>
{% if users %}
 <ol>

     {% for i in users %}
     <li>
     <ul>
         <li> {{ i.f_name|cut:'a' }}</li>
         <li> {{ i.l_name|upper }}</li>
         <li> {{ i.email }}</li>
     </ul>
     </li><br>

     {% endfor %}
 </ol>

{% endif %}

{% endblock %}